# Generated by Django 5.2.7 on 2025-10-20 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('ingredients', models.TextField(blank=True, verbose_name='Ингредиенты')),
                ('steps', models.TextField(blank=True, verbose_name='Шаги')),
                ('duration', models.CharField(blank=True, max_length=100, verbose_name='Время приготовления')),
            ],
        ),
    ]
