# Generated by Django 5.2.7 on 2025-10-20 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='duration1',
            field=models.CharField(blank=True, max_length=100, verbose_name='Время приготовления'),
        ),
    ]
