# Generated by Django 5.2.7 on 2025-10-20 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_duration1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='duration1',
        ),
    ]
