# Generated by Django 5.2.7 on 2025-10-20 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_remove_recipe_duration1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='duration',
            field=models.PositiveIntegerField(blank=True, max_length=5, verbose_name='Время приготовления'),
        ),
    ]
