# Generated by Django 5.2.7 on 2025-10-20 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_recipe_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='duration',
            field=models.CharField(blank=True, max_length=50, verbose_name='Время приготовления'),
        ),
    ]
