# Generated by Django 5.2.7 on 2025-10-20 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_recipe_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='author',
            field=models.TextField(default=5, verbose_name='Автор'),
            preserve_default=False,
        ),
    ]
