# Generated by Django 5.2.7 on 2025-10-27 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_remove_recipe_author_remove_recipe_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='author',
            field=models.TextField(blank=True, verbose_name='Автор'),
        ),
    ]
