# Generated by Django 5.2.7 on 2025-11-07 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_remove_recipe_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='colories',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Каллорийность'),
            preserve_default=False,
        ),
    ]
