# Generated by Django 5.2.7 on 2025-11-07 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_recipe_colories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='colories',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Каллорийность'),
        ),
    ]
