# Generated by Django 5.2.7 on 2025-11-07 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_alter_recipe_colories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='colories',
        ),
    ]
