# Generated by Django 5.2.7 on 2025-11-07 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_remove_recipe_colories'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='colories',
            field=models.BooleanField(default=True, verbose_name='Диетическое'),
            preserve_default=False,
        ),
    ]
